<?php
$submiturl   = $this->helper('avrequestprice')->submitFormUrl();
$customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
if ($customer_id != "") {
    $customerData = Mage::getModel('customer/customer')->load($customer_id);
}
?>
<div class="callprice_request_form">
    <form action="<?php echo $this->getFormAction() ?>" name="rprice_form" id="rprice_form" method="post">
        <div class="fieldset">

            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label class="required" for="name"><em>*</em><?php echo $this->__('Name') ?></label>
                        <div class="input-box">
                            <input id="name" name="name" type="text" class="input-text required-entry" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getName() ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label class="required" for="email"><em>*</em><?php echo $this->__('Email') ?></label>
                        <div class="input-box">
                            <input id="email" name="email" type="text" class="input-text required-entry validate-email" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail() ?>"/>
                        </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="comment"><?php echo $this->__('Comment') ?></label>
                    <div class="input-box">
                        <textarea rows="3" cols="5" class="input-text" title="comment" id="comment" name="comment"></textarea>
                    </div>
                </li>
            </ul>
            <div>
                <button type="button" class="button" onclick="if (dataForm.validator && dataForm.validator.validate()) {
                            submitRequestPriceForm(this.form, '<?php echo $submiturl ?>');
                        }"><span><span><?php echo $this->__('Submit Request') ?></span></span></button>
            </div>
        </div>
        <input type="hidden" name="product_id" value="<?php echo $this->getProductId(); ?>"/>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('rprice_form', true);
    //]]>
</script>
